### ISSUE TITLE
Consider combining work?

### ISSUE THREAD

**Issue by xloem** [chbergmann/LasercutterSVGExport#2]
Hey,

I found your project first, and then found https://github.com/execuc/LCInterlocking .  I thought if you ever wanted to help the ecosystem out, contributing this work to that project could improve things.

**Comment by chbergmann** [comment]
The LCInterlocking workbench is complicated to use and it integrates the width of the laser beam into the design. This is not a good design practice. I consider the LasercutterSVGExport marcro as an alternative.
